[package]
name = "rest-project"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
html5ever = "0.35.0"
markup5ever_rcdom = "0.35.0"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
sqlx = "0.8.6"
